services:
  app:
    build:
      context: ./docker/app
    user: "1000:1000"

    depends_on:
      - db
    volumes:
      - ./:/src
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini

  scheduler:
    build:
      context: ./docker/app   # app と同じビルドを使う
    user: "1000:1000"
    depends_on:
      - app
      - db
      - redis
    volumes:
      - ./:/src               # artisan にアクセス
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    working_dir: /src
    restart: always
    entrypoint: [ "sh", "-lc" ]
    command: >
      'while true; do
         php artisan schedule:run --no-interaction >> /src/storage/logs/scheduler.log 2>&1;
         sleep 60;
       done'
  
  node:
    build:
      context: ./docker/node
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./:/src
  
  db:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=database #データベース名
      - MYSQL_HOST=mysql
      - MYSQL_USER=user #ユーザ名
      - MYSQL_PASSWORD=pass #ユーザパスワード
      - MYSQL_ROOT_PASSWORD=root_pass #ルートユーザーのパスワード
      - TZ=Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/src
      - ./docker/nginx/logs:/src/docker/nginx/logs

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  queue:
    build:
      context: ./docker/app
    depends_on:
      - app
      - redis
      - db
    working_dir: /src
    volumes:
      - ./:/src
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    restart: always
    command: php artisan queue:work --sleep=1 --tries=3 --queue=default,broadcasts
